"""initial_clean_state

Revision ID: 11f67fda1e7a
Revises: 
Create Date: 2026-04-17 19:32:32.183066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f67fda1e7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performers_id'), 'performers', ['id'], unique=False)
    op.create_index(op.f('ix_performers_name'), 'performers', ['name'], unique=True)
    op.create_table('venues',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('province', sa.Enum('ANTWERP', 'EAST_FLANDERS', 'FLEMISH_BRABANT', 'LIMBURG', 'WEST_FLANDERS', name='province'), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scraper_config', sa.JSON(), nullable=True),
    sa.Column('last_scraped_at', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=True)
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concerts_content_hash'), 'concerts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_concerts_id'), 'concerts', ['id'], unique=False)
    op.create_index(op.f('ix_concerts_url'), 'concerts', ['url'], unique=False)
    op.create_table('concert_performers',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('concert_id', 'performer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concert_performers')
    op.drop_index(op.f('ix_concerts_url'), table_name='concerts')
    op.drop_index(op.f('ix_concerts_id'), table_name='concerts')
    op.drop_index(op.f('ix_concerts_content_hash'), table_name='concerts')
    op.drop_table('concerts')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_performers_name'), table_name='performers')
    op.drop_index(op.f('ix_performers_id'), table_name='performers')
    op.drop_table('performers')
    # ### end Alembic commands ###
