"""Add tracking fields to concerts

Revision ID: e402fc14a483
Revises: 826c857dc099
Create Date: 2026-04-17 13:10:33.465628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e402fc14a483'
down_revision: Union[str, Sequence[str], None] = '826c857dc099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concerts', sa.Column('url', sa.String(), nullable=True))
    op.add_column('concerts', sa.Column('status', sa.String(), nullable=True))
    # Seed existing records with 'active'
    op.execute("UPDATE concerts SET status = 'active' WHERE status IS NULL")
    # Now set it to NOT NULL
    op.alter_column('concerts', 'status', nullable=False)
    
    op.add_column('concerts', sa.Column('last_scraped_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_concerts_url'), 'concerts', ['url'], unique=False)
    op.drop_column('concerts', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concerts', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_concerts_url'), table_name='concerts')
    op.drop_column('concerts', 'last_scraped_at')
    op.drop_column('concerts', 'status')
    op.drop_column('concerts', 'url')
    # ### end Alembic commands ###
