services:
  db:
    image: postgres:17-alpine
    container_name: concert_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: poc-concert-notifications
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ..             
      dockerfile: docker/Dockerfile
    container_name: concert_api
    volumes:
      - ..:/app              
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/poc-concert-notifications
    depends_on:
      - db

volumes:
  postgres_data: